# 1. Create numpy

In [1]:
import numpy as np

oneDArray = np.array([1,2,3,4])

twoDArray = np.array([
    [1,2,3],
    [4,5,6]
])

threeDArray = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [2]:
# dtype set
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [3]:
# range
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Shape change

In [5]:
oneDArray

array([1, 2, 3, 4])

In [6]:
oneDArray.reshape(2,2)

array([[1, 2],
       [3, 4]])

# one and zeros and random

In [7]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.random.random((4,2))           # 0-1

array([[0.91379161, 0.58611263],
       [0.83612669, 0.26714205],
       [0.00423459, 0.15610878],
       [0.80500069, 0.2317888 ]])

# Linespace

In [10]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

# identity mat

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attribute

In [13]:
np.arange(4, dtype=np.int32)

array([0, 1, 2, 3], dtype=int32)

In [15]:
np.arange(6, dtype=np.float32).reshape(3,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)

In [16]:
threeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
# dimension
threeDArray.ndim

3

In [18]:
# shape
threeDArray.shape

(2, 2, 3)

In [19]:
# type
threeDArray.dtype

dtype('int64')

In [20]:
threeDArray.astype(np.float32)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)

In [22]:
a1 = np.arange(12,18, dtype=np.float32).reshape(2,3)
a2 = np.arange(12,42, dtype=np.float32).reshape(6,5)

# Matrix Operation

In [23]:
twoDArray

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# scalar multiplication
twoDArray * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
# element wise power
twoDArray ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
# element wise check
twoDArray == 5

array([[False, False, False],
       [False,  True, False]])

In [27]:
# element wise multiplication
twoDArray * a1

array([[ 12.,  26.,  42.],
       [ 60.,  80., 102.]])

# Array function

In [29]:
arr = (np.random.random(6).reshape(2,3)) * 25
arr

array([[ 8.08750553, 10.63433213, 22.62799393],
       [14.80615751,  4.00392599,  9.03122647]])

In [30]:
np.round(arr)

array([[ 8., 11., 23.],
       [15.,  4.,  9.]])

In [31]:
np.ceil(arr)

array([[ 9., 11., 23.],
       [15.,  5., 10.]])

In [32]:
np.floor(arr)

array([[ 8., 10., 22.],
       [14.,  4.,  9.]])

In [33]:
np.min(arr)

np.float64(4.003925988239446)

In [34]:
np.max(arr)

np.float64(22.627993926182054)

In [35]:
np.sum(arr)

np.float64(69.19114155862597)

In [36]:
np.prod(arr)

np.float64(1041947.8993239967)

In [37]:
arr

array([[ 8.08750553, 10.63433213, 22.62799393],
       [14.80615751,  4.00392599,  9.03122647]])

# Column wise (axis = 0)

In [38]:
np.max(arr, axis=0)

array([14.80615751, 10.63433213, 22.62799393])

# Row wise (axis = 1)

In [39]:
np.max(arr, axis=1)

array([22.62799393, 14.80615751])

# Statistical function

In [40]:
np.mean(arr, axis=0)

array([11.44683152,  7.31912906, 15.8296102 ])

In [41]:
np.median(arr, axis=0)

array([11.44683152,  7.31912906, 15.8296102 ])

In [42]:
np.std(arr, axis=1)

array([6.33999695, 4.41351189])

In [43]:
np.var(arr, axis=1)

array([40.1955613 , 19.47908718])

# math function

In [44]:
np.sin(arr)

array([[ 0.97285698, -0.93545852, -0.59466214],
       [ 0.78444811, -0.75936285,  0.38347082]])

In [45]:
np.log(arr)

array([[2.09032034, 2.36408765, 3.11918781],
       [2.69504314, 1.38727538, 2.20068818]])

# matrix dot product

In [48]:
arr2 = np.random.random(12).reshape(3,4) * 25
arr2

array([[ 0.61484679, 13.22373481,  5.98320867,  6.57467178],
       [ 6.69153101, 17.80765092, 14.36520355,  2.03519921],
       [14.1048802 , 19.11577362,  6.61309415, 22.75264885]])

In [49]:
np.dot(arr, arr2)

array([[395.29768352, 728.87111226, 350.79463325, 589.66247866],
       [163.28028073, 439.73209756, 205.82989276, 310.97873742]])

# Indexing

In [50]:
oneDArray

array([1, 2, 3, 4])

In [51]:
oneDArray[2]

np.int64(3)

In [52]:
twoDArray

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
twoDArray[1,2]

np.int64(6)

In [56]:
threeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
threeDArray[0,1,2]

np.int64(6)

# Slicing

In [59]:
oneDArray

array([1, 2, 3, 4])

In [58]:
oneDArray[1:3]

array([2, 3])

In [65]:
twoDArray = np.random.random(20).reshape(4,5) * 25
twoDArray

array([[19.66597145,  1.91665589, 16.71713274, 15.0287304 ,  1.15261752],
       [18.28318812,  5.72415429, 10.62414243, 22.95851023, 12.34702162],
       [15.34158606,  6.67682215,  2.54250524, 16.43517522, 23.08139011],
       [17.73679274,  1.69614215, 15.39798432,  2.61799053, 21.88161783]])

In [67]:
twoDArray[1:4, 1:3]

array([[ 5.72415429, 10.62414243],
       [ 6.67682215,  2.54250524],
       [ 1.69614215, 15.39798432]])

In [68]:
twoDArray[[1,2]]  # twoDArray[[1,2] , :]

array([[18.28318812,  5.72415429, 10.62414243, 22.95851023, 12.34702162],
       [15.34158606,  6.67682215,  2.54250524, 16.43517522, 23.08139011]])

In [69]:
threeDArray[0:1, 1:3, 0:2]

array([[[4, 5]]])

# Transpose

In [70]:
twoDArray.T

array([[19.66597145, 18.28318812, 15.34158606, 17.73679274],
       [ 1.91665589,  5.72415429,  6.67682215,  1.69614215],
       [16.71713274, 10.62414243,  2.54250524, 15.39798432],
       [15.0287304 , 22.95851023, 16.43517522,  2.61799053],
       [ 1.15261752, 12.34702162, 23.08139011, 21.88161783]])

# 1D Convert

In [71]:
twoDArray.ravel()

array([19.66597145,  1.91665589, 16.71713274, 15.0287304 ,  1.15261752,
       18.28318812,  5.72415429, 10.62414243, 22.95851023, 12.34702162,
       15.34158606,  6.67682215,  2.54250524, 16.43517522, 23.08139011,
       17.73679274,  1.69614215, 15.39798432,  2.61799053, 21.88161783])

# hstack

In [72]:
arr1 = np.random.random(6).reshape(2,3) * 25
arr2 = np.random.random(6).reshape(2,3) * 25

In [75]:
hMergeArr = np.hstack((arr1, arr2))
hMergeArr

array([[23.96059575,  5.94495031, 14.21906079,  3.0507935 ,  4.62811375,
        11.20460234],
       [ 4.67228845,  4.48272487, 18.43669682, 19.65790857,  9.51011699,
        15.18478199]])

# hsplit

In [76]:
np.hsplit(hMergeArr, 3)

[array([[23.96059575,  5.94495031],
        [ 4.67228845,  4.48272487]]),
 array([[14.21906079,  3.0507935 ],
        [18.43669682, 19.65790857]]),
 array([[ 4.62811375, 11.20460234],
        [ 9.51011699, 15.18478199]])]

# vstack

In [78]:
vMergeArr = np.vstack((arr1, arr2))
vMergeArr

array([[23.96059575,  5.94495031, 14.21906079],
       [ 4.67228845,  4.48272487, 18.43669682],
       [ 3.0507935 ,  4.62811375, 11.20460234],
       [19.65790857,  9.51011699, 15.18478199]])

# vsplit

In [79]:
np.vsplit(vMergeArr, 2)

[array([[23.96059575,  5.94495031, 14.21906079],
        [ 4.67228845,  4.48272487, 18.43669682]]),
 array([[ 3.0507935 ,  4.62811375, 11.20460234],
        [19.65790857,  9.51011699, 15.18478199]])]