In [1]:
import numpy as np

In [2]:
arr = np.random.random(24).reshape(4,6) * 25
arr

array([[18.20068675,  5.19291523, 14.8641881 ,  9.11486334, 16.98562323,
        21.32121562],
       [13.18904849, 21.66849322, 20.30228516, 19.43220399,  6.172053  ,
        12.21544619],
       [ 9.56955089,  8.31941771,  5.60576402, 13.30125571, 19.0733739 ,
         1.49888533],
       [15.44670478, 23.62822233, 10.0733152 , 21.81742676,  9.33280017,
        15.62550208]])

### 1.Extract the first row

In [3]:
arr[0, :]

array([18.20068675,  5.19291523, 14.8641881 ,  9.11486334, 16.98562323,
       21.32121562])

### 2.Extract the first column

In [4]:
arr[:, 0]

array([18.20068675, 13.18904849,  9.56955089, 15.44670478])

### 3.Extract the last row

In [5]:
arr[-1, :]

array([15.44670478, 23.62822233, 10.0733152 , 21.81742676,  9.33280017,
       15.62550208])

### 4.Extract the last column

In [6]:
arr[:,-1]

array([21.32121562, 12.21544619,  1.49888533, 15.62550208])

### 5.Extract a submatrix (first 2 rows and 3 columns)

In [7]:
arr[:2, :3]

array([[18.20068675,  5.19291523, 14.8641881 ],
       [13.18904849, 21.66849322, 20.30228516]])

### 6. Reverse the rows of a 2D array

In [8]:
arr[::-1 , :]

array([[15.44670478, 23.62822233, 10.0733152 , 21.81742676,  9.33280017,
        15.62550208],
       [ 9.56955089,  8.31941771,  5.60576402, 13.30125571, 19.0733739 ,
         1.49888533],
       [13.18904849, 21.66849322, 20.30228516, 19.43220399,  6.172053  ,
        12.21544619],
       [18.20068675,  5.19291523, 14.8641881 ,  9.11486334, 16.98562323,
        21.32121562]])

# Boolean Indexing

In [9]:
arr > 10

array([[ True, False,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [False, False, False,  True,  True, False],
       [ True,  True,  True,  True, False,  True]])

In [10]:
arr[ arr > 10]

array([18.20068675, 14.8641881 , 16.98562323, 21.32121562, 13.18904849,
       21.66849322, 20.30228516, 19.43220399, 12.21544619, 13.30125571,
       19.0733739 , 15.44670478, 23.62822233, 10.0733152 , 21.81742676,
       15.62550208])

In [11]:
arr2 = np.random.randint(1,25 , (4,6))
arr2

array([[10, 24, 15,  1, 19, 19],
       [13, 13,  5,  8,  8,  3],
       [ 7, 17,  1,  9,  5,  6],
       [18,  5, 22,  5,  9, 21]], dtype=int32)

In [12]:
arr2 % 2 == 0

array([[ True,  True, False, False, False, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False, False,  True],
       [ True, False,  True, False, False, False]])

In [13]:
(arr2 % 2 == 0) & (arr2 > 10)

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False,  True, False, False, False]])

In [14]:
arr2[ arr2 % 2 == 0 ]

array([10, 24,  8,  8,  6, 18, 22], dtype=int32)

In [15]:
arr2[ (arr2 % 2 == 0) & (arr2 > 10) ]

array([24, 18, 22], dtype=int32)

# Missing Value Check

In [16]:
misArr = np.array([
    [1,np.nan],
    [3,4]
])
misArr

array([[ 1., nan],
       [ 3.,  4.]])

In [17]:
np.isnan(misArr)

array([[False,  True],
       [False, False]])

In [18]:
misArr[ np.isnan(misArr) ]

array([nan])

In [19]:
misArr[ ~ np.isnan(misArr) ]

array([1., 3., 4.])

# Random Number