In [1]:
import numpy as np

In [2]:
arr = np.random.random(24).reshape(4,6) * 25
arr

array([[23.68227942, 22.85614599,  1.43357213,  7.30545137,  6.50812767,
         1.5455917 ],
       [ 2.02514683, 14.19605179,  4.33611345, 23.94310875,  3.9292599 ,
        22.30763949],
       [11.44054571, 12.56928617, 22.80312911, 19.54748474, 17.50759872,
         9.4145236 ],
       [17.21337689,  6.92249838,  5.08185122, 19.81169117, 12.17235063,
        12.59868569]])

### 1.Extract the first row

In [3]:
arr[0, :]

array([23.68227942, 22.85614599,  1.43357213,  7.30545137,  6.50812767,
        1.5455917 ])

### 2.Extract the first column

In [4]:
arr[:, 0]

array([23.68227942,  2.02514683, 11.44054571, 17.21337689])

### 3.Extract the last row

In [5]:
arr[-1, :]

array([17.21337689,  6.92249838,  5.08185122, 19.81169117, 12.17235063,
       12.59868569])

### 4.Extract the last column

In [6]:
arr[:,-1]

array([ 1.5455917 , 22.30763949,  9.4145236 , 12.59868569])

### 5.Extract a submatrix (first 2 rows and 3 columns)

In [7]:
arr[:2, :3]

array([[23.68227942, 22.85614599,  1.43357213],
       [ 2.02514683, 14.19605179,  4.33611345]])

### 6. Reverse the rows of a 2D array

In [8]:
arr[::-1 , :]

array([[17.21337689,  6.92249838,  5.08185122, 19.81169117, 12.17235063,
        12.59868569],
       [11.44054571, 12.56928617, 22.80312911, 19.54748474, 17.50759872,
         9.4145236 ],
       [ 2.02514683, 14.19605179,  4.33611345, 23.94310875,  3.9292599 ,
        22.30763949],
       [23.68227942, 22.85614599,  1.43357213,  7.30545137,  6.50812767,
         1.5455917 ]])

# Boolean Indexing

In [9]:
arr > 10

array([[ True,  True, False, False, False, False],
       [False,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False],
       [ True, False, False,  True,  True,  True]])

In [10]:
arr[ arr > 10]

array([23.68227942, 22.85614599, 14.19605179, 23.94310875, 22.30763949,
       11.44054571, 12.56928617, 22.80312911, 19.54748474, 17.50759872,
       17.21337689, 19.81169117, 12.17235063, 12.59868569])

In [11]:
arr2 = np.random.randint(1,25 , (4,6))
arr2

array([[17,  1, 17,  7,  3,  1],
       [ 3, 22,  3, 10,  1, 23],
       [11, 24, 15, 23,  4, 23],
       [22, 24,  5, 24, 16, 10]], dtype=int32)

In [12]:
arr2 % 2 == 0

array([[False, False, False, False, False, False],
       [False,  True, False,  True, False, False],
       [False,  True, False, False,  True, False],
       [ True,  True, False,  True,  True,  True]])

In [13]:
(arr2 % 2 == 0) & (arr2 > 10)

array([[False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False,  True, False, False, False, False],
       [ True,  True, False,  True,  True, False]])

In [14]:
arr2[ arr2 % 2 == 0 ]

array([22, 10, 24,  4, 22, 24, 24, 16, 10], dtype=int32)

In [15]:
arr2[ (arr2 % 2 == 0) & (arr2 > 10) ]

array([22, 24, 22, 24, 24, 16], dtype=int32)

# Missing Value Check

In [16]:
misArr = np.array([
    [1,np.nan],
    [3,4]
])
misArr

array([[ 1., nan],
       [ 3.,  4.]])

In [17]:
np.isnan(misArr)

array([[False,  True],
       [False, False]])

In [18]:
misArr[ np.isnan(misArr) ]

array([nan])

In [19]:
misArr[ ~ np.isnan(misArr) ]

array([1., 3., 4.])

# Random Number

In [20]:
# 0-1
np.random.rand(2,3) 

array([[0.02734035, 0.60464198, 0.11390643],
       [0.72307828, 0.01770871, 0.45022124]])

In [22]:
# standard
np.random.randn(3,3)

array([[ 2.19092565, -0.9565615 ,  0.41845941],
       [-1.79006879, -0.42490426, -0.69353081],
       [ 0.82673225,  1.46725617,  0.24474269]])

In [21]:
# int
np.random.randint(1,10, (2,3))

array([[9, 5, 4],
       [8, 6, 2]], dtype=int32)

In [23]:
# float
np.random.uniform(1,10, (2,3))

array([[4.09366692, 5.80789596, 8.80858946],
       [1.63513866, 6.5370134 , 1.29443678]])

# Broadcasting

In [25]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (3,4))
arr1 + arr2

array([[ 8,  8, 12, 17],
       [18, 18, 16, 15],
       [27, 14, 19, 22]], dtype=int32)

In [26]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (3))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [27]:
arr1 = np.random.randint(1,20, (1,3))
arr2 = np.random.randint(1,20, (4,3))
arr1 + arr2

array([[12, 15,  9],
       [15, 14,  3],
       [14, 17, 18],
       [18, 20, 13]], dtype=int32)

In [28]:
arr1 = np.random.randint(1,20, (1))
arr2 = np.random.randint(1,20, (2,2))
arr1 + arr2

array([[25, 22],
       [31, 18]], dtype=int32)

In [29]:
arr1 = np.random.randint(1,20, (3,4))
arr2 = np.random.randint(1,20, (4,3))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [30]:
arr1 = np.random.randint(1,20, (4,4))
arr2 = np.random.randint(1,20, (2,2))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 