In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

array([[ 0.07076875,  0.05068012,  0.01211685, ...,  0.03430886,
         0.02736405, -0.0010777 ],
       [-0.00914709,  0.05068012, -0.01806189, ...,  0.07120998,
         0.00027248,  0.01963284],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703607, -0.01350402],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]], shape=(353, 10))

In [4]:
class StochasticGradientDescent:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.intercept = None
        self.coef = None
        
    def fit(self, X_train, y_train):
        no_of_rows = X_train.shape[0]
        no_of_cols = X_train.shape[1]
        
        # 1. Initialize Intercept and Coef
        self.intercept = 0
        self.coef = np.ones(no_of_cols)
        
        for epoch in range(self.epochs):
            for ithRow in range(no_of_rows):
                y_hat = np.dot(self.coef , X_train[ithRow]) + self.intercept
                
                # 2. Calculate Gradient
                dL_by_dB0 = -2 * (y_train[ithRow] - y_hat)
                dL_by_dB1 = -2 * np.dot((y_train[ithRow] - y_hat), X_train[ithRow])
                
                # 3. Update Intercept and Coef
                self.intercept -= (self.learning_rate * dL_by_dB0)
                self.coef -= (self.learning_rate * dL_by_dB1)
                
    def predict(self, X_test):
        return np.dot(X_test, self.coef) + self.intercept

In [5]:
sgdReg = StochasticGradientDescent(learning_rate=0.01,epochs=100)

In [6]:
sgdReg.fit(X_train,y_train)

In [7]:
y_pred = sgdReg.predict(X_test)
y_pred

array([144.80286044, 171.35913165, 144.10374946, 281.9115881 ,
       127.79746418, 102.91174894, 245.50881446, 193.1412854 ,
        91.25488188, 118.30333813,  97.86811719, 147.84950088,
        65.59119677, 208.05887615, 108.35257627, 134.08758271,
       220.55489574, 242.50356588, 186.82124739, 210.25690852,
       192.77124506,  90.89242405,  78.35169468, 186.71443463,
       149.72506348, 163.13120377, 184.01234941, 173.57246792,
        53.34075087, 120.80688694, 175.1835747 ,  95.20091949,
       133.2247251 , 180.29052669, 170.64460199, 188.443439  ,
       128.39332609, 127.06315359, 155.57988161,  62.55931551,
        84.79756645, 114.82281247, 154.97082067, 154.8889198 ,
       171.02737254,  68.01768441,  82.61203522, 104.39599082,
        63.03360822, 149.87275144, 145.45627218,  66.09413208,
       117.76647907, 109.58484399, 171.764562  , 148.81244929,
       101.12557052, 196.92025368, 112.99534207,  69.09601444,
       181.49627589, 188.13447931, 138.75362089, 115.74

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4581571751249822