In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

array([[ 0.07076875,  0.05068012,  0.01211685, ...,  0.03430886,
         0.02736405, -0.0010777 ],
       [-0.00914709,  0.05068012, -0.01806189, ...,  0.07120998,
         0.00027248,  0.01963284],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703607, -0.01350402],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]], shape=(353, 10))

In [16]:
from sklearn.linear_model import SGDRegressor
miniBatchReg = SGDRegressor(learning_rate='constant', eta0=0.1)

In [17]:
import random
epochs = 100
batch_size = 35

no_of_rows = X_train.shape[0]

for epoch in range(epochs):
    batch_indexes = random.sample(range(no_of_rows), batch_size)
    miniBatchReg.partial_fit(X_train[batch_indexes], y_train[batch_indexes])

In [18]:
y_pred = miniBatchReg.predict(X_test)
y_pred

array([164.53871185, 179.43200153, 165.06414102, 280.24428541,
       151.06680658, 126.62516518, 244.03202337, 206.06390486,
       115.59135688, 138.67185546, 116.64142503, 156.79314731,
        83.54710445, 219.04636839, 131.69295151, 149.29756241,
       229.34615258, 248.25263213, 189.60700437, 218.26144972,
       192.40516471, 115.41938751,  99.50542389, 199.0048081 ,
       156.24346743, 178.50077361, 192.88263144, 186.94900527,
        75.32763122, 145.68839377, 184.92283218, 112.62201506,
       153.36671098, 194.48551993, 186.56950396, 193.96009964,
       150.02764242, 151.19700127, 179.38464619,  87.05872844,
       108.45958592, 137.04884852, 168.94489709, 180.26039042,
       180.5999985 ,  89.76535541, 101.48695343, 119.71263662,
        86.35133963, 156.43718083, 151.64151115,  86.35183858,
       142.31173064, 127.86759318, 186.45922159, 153.77419464,
       122.73833814, 203.23880952, 127.02502356,  88.47626244,
       191.3082408 , 189.59242491, 150.04508674, 137.98

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4249049755828035