In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
from sklearn.datasets import load_diabetes
X, y = load_diabetes(return_X_y=True)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train

array([[ 0.07076875,  0.05068012,  0.01211685, ...,  0.03430886,
         0.02736405, -0.0010777 ],
       [-0.00914709,  0.05068012, -0.01806189, ...,  0.07120998,
         0.00027248,  0.01963284],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703607, -0.01350402],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]], shape=(353, 10))

In [11]:
class BatchGradientDescentRegressor:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.coef = None
        self.intercept = None
    
    def fit(self,X_train, y_train):
        no_of_rows = X_train.shape[0]
        no_of_cols = X_train.shape[1]
        
        # 1. Initialize Intercept and Coef
        self.intercept = 0
        self.coef = np.random.random(no_of_cols)
        
        for epoch in range(self.epochs):
            y_hat = self.intercept + np.dot(X_train, self.coef)
            
            # 2. Calculate Gradient
            dL_by_dB0 = (-2 * np.sum(y_train - y_hat)) / no_of_rows
            dL_by_dB1 = (-2 * np.dot(y_train - y_hat, X_train)) / no_of_rows
            
            # 3. Update Intercept and Coef
            self.intercept -= (self.learning_rate * dL_by_dB0)
            self.coef -= (self.learning_rate * dL_by_dB1)
    
    def predict(self, X_test):
        return np.dot(X_test, self.coef) + self.intercept
    

In [12]:
bGd = BatchGradientDescentRegressor(learning_rate=0.5,epochs=500)

In [13]:
bGd.fit(X_train, y_train)

In [14]:
bGd.intercept, bGd.coef

(np.float64(151.63761401884682),
 array([  52.88434897, -130.61934881,  419.51724248,  282.25782077,
         -25.74315531,  -69.66314744, -198.71626183,  148.52786086,
         320.53410717,  144.91855497]))

In [15]:
y_pred = bGd.predict(X_test)
y_pred

array([151.72936623, 169.42798719, 150.09378447, 279.44931352,
       135.28456005, 110.86290543, 241.95282603, 197.58922908,
        97.90738269, 124.28035153, 102.11286353, 145.50994637,
        67.26681952, 210.55329113, 114.35778534, 135.73722163,
       221.94500026, 242.90490085, 181.81435977, 210.55700016,
       187.79586198,  97.62300756,  82.86113834, 188.39843189,
       147.77393429, 165.91911098, 183.5452047 , 175.27121532,
        56.9238897 , 128.92675004, 176.20797882,  98.99017846,
       138.35580693, 183.1953682 , 174.89974496, 187.98438678,
       134.34276454, 135.10338382, 163.89900075,  67.7321217 ,
        90.9444064 , 119.74905735, 155.66054323, 163.50026815,
       170.74943178,  72.47740518,  86.14279901, 104.4561592 ,
        67.63302167, 147.64847314, 141.52133814,  69.71211674,
       125.52411173, 112.70197487, 176.8979058 , 145.30204485,
       107.26945075, 194.71508808, 113.83135202,  71.15737595,
       183.97176354, 183.88468964, 138.49704905, 121.51

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4560147546736246